<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * @return array<string, array{    // Import name as key, description of the imported file as value
 *     path: string,               // Logical, relative or absolute path to the file
 *     type?: 'js'|'css'|'json',   // Type of the file, defaults to 'js'
 *     entrypoint?: bool,          // Whether the file is an entrypoint, for 'js' only
 * }|array{
 *     version: string,            // Version of the remote package
 *     package_specifier?: string, // Remote "package-name/path" specifier, defaults to the import name
 *     type?: 'js'|'css'|'json',
 *     entrypoint?: bool,
 *     esm?: bool,                 // Whether jsDelivr's ESM build is used, defaults to true
 * }>
 */
return [
    '@floating-ui/core' => ['version' => '1.8.0'],
    '@floating-ui/dom' => ['version' => '1.8.0'],
    '@floating-ui/utils' => ['version' => '0.2.12'],
    '@floating-ui/utils/dom' => ['version' => '0.2.12'],
    '@hotwired/stimulus' => ['version' => '3.2.2'],
    '@hpcc-js/wasm/graphviz' => ['version' => '2.20.0'],
    '@kurkle/color' => ['version' => '0.4.0'],
    '@popperjs/core' => ['version' => '2.11.8'],
    '@stimulus-components/timeago' => ['version' => '5.0.2'],
    '@symfony/stimulus-bundle' => ['path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js'],
    '@tabler/core' => ['version' => '1.6.1'],
    '@tabler/core/dist/css/tabler.min.css' => ['version' => '1.6.1', 'type' => 'css'],
    '@tacman1123/twig-browser' => ['version' => '1.0.0'],
    '@tacman1123/twig-browser/adapters/symfony' => ['version' => '1.0.0'],
    '@tacman1123/twig-browser/src/compat/compileTwigBlocks.js' => ['version' => '1.0.0'],
    'admin' => ['path' => './assets/admin.js', 'entrypoint' => true],
    'app' => ['path' => './assets/app.js', 'entrypoint' => true],
    'bootstrap' => ['version' => '5.3.8'],
    'bootstrap/dist/css/bootstrap.min.css' => ['version' => '5.3.8', 'type' => 'css'],
    'chart.js' => ['version' => '4.5.1'],
    'd3-color' => ['version' => '3.0.1'],
    'd3-dispatch' => ['version' => '3.0.1'],
    'd3-drag' => ['version' => '3.0.0'],
    'd3-ease' => ['version' => '3.0.1'],
    'd3-format' => ['version' => '3.1.0'],
    'd3-graphviz' => ['version' => '5.6.0'],
    'd3-interpolate' => ['version' => '3.0.1'],
    'd3-path' => ['version' => '3.1.0'],
    'd3-selection' => ['version' => '3.0.0'],
    'd3-timer' => ['version' => '3.0.1'],
    'd3-transition' => ['version' => '3.0.1'],
    'd3-zoom' => ['version' => '3.0.0'],
    'datatables.net' => ['version' => '3.1.3'],
    'datatables.net-bs' => ['version' => '3.1.2'],
    'datatables.net-bs/css/dataTables.bootstrap.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-bs4' => ['version' => '3.1.2'],
    'datatables.net-bs4/css/dataTables.bootstrap4.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-bs5' => ['version' => '3.1.3'],
    'datatables.net-bs5/css/dataTables.bootstrap5.css' => ['version' => '3.1.3', 'type' => 'css'],
    'datatables.net-bs5/css/dataTables.bootstrap5.min.css' => ['version' => '3.1.3', 'type' => 'css'],
    'datatables.net-buttons' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs/css/buttons.bootstrap.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-buttons-bs4' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-buttons-bs5' => ['version' => '4.1.2'],
    'datatables.net-buttons-bs5/css/buttons.bootstrap5.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-buttons-dt' => ['version' => '4.1.2'],
    'datatables.net-buttons-dt/css/buttons.dataTables.min.css' => ['version' => '4.1.2', 'type' => 'css'],
    'datatables.net-colreorder' => ['version' => '3.1.2'],
    'datatables.net-colreorder-bs' => ['version' => '3.1.2'],
    'datatables.net-colreorder-bs/css/colReorder.bootstrap.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-colreorder-bs4' => ['version' => '3.1.2'],
    'datatables.net-colreorder-bs4/css/colReorder.bootstrap4.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-colreorder-bs5' => ['version' => '3.1.2'],
    'datatables.net-colreorder-bs5/css/colReorder.bootstrap5.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-colreorder-dt' => ['version' => '3.1.2'],
    'datatables.net-colreorder-dt/css/colReorder.dataTables.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-columncontrol' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-bs' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-bs/css/columnControl.bootstrap.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-bs4' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-bs4/css/columnControl.bootstrap4.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-bs5' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-bs5/css/columnControl.bootstrap5.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-bs5/css/columnControl.bootstrap5.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-columncontrol-dt' => ['version' => '2.1.2'],
    'datatables.net-columncontrol-dt/css/columnControl.dataTables.min.css' => ['version' => '2.1.2', 'type' => 'css'],
    'datatables.net-dt' => ['version' => '3.1.2'],
    'datatables.net-dt/css/dataTables.dataTables.min.css' => ['version' => '3.1.2', 'type' => 'css'],
    'datatables.net-fixedcolumns' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs/css/fixedColumns.bootstrap.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-bs4' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs4/css/fixedColumns.bootstrap4.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-bs5' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedcolumns-dt' => ['version' => '6.1.1'],
    'datatables.net-fixedcolumns-dt/css/fixedColumns.dataTables.min.css' => ['version' => '6.1.1', 'type' => 'css'],
    'datatables.net-fixedheader' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-bs' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-fixedheader-bs4' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-bs4/css/fixedHeader.bootstrap4.min.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-fixedheader-bs5' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-fixedheader-dt' => ['version' => '5.1.2'],
    'datatables.net-fixedheader-dt/css/fixedHeader.dataTables.min.css' => ['version' => '5.1.2', 'type' => 'css'],
    'datatables.net-keytable' => ['version' => '3.1.1'],
    'datatables.net-keytable-bs' => ['version' => '3.1.1'],
    'datatables.net-keytable-bs/css/keyTable.bootstrap.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-keytable-bs4' => ['version' => '3.1.1'],
    'datatables.net-keytable-bs4/css/keyTable.bootstrap4.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-keytable-bs5' => ['version' => '3.1.1'],
    'datatables.net-keytable-bs5/css/keyTable.bootstrap5.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-keytable-dt' => ['version' => '3.1.1'],
    'datatables.net-keytable-dt/css/keyTable.dataTables.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-plugins/i18n/de-DE.mjs' => ['version' => '3.1.2'],
    'datatables.net-plugins/i18n/en-GB.mjs' => ['version' => '3.1.2'],
    'datatables.net-plugins/i18n/es-ES.mjs' => ['version' => '3.1.2'],
    'datatables.net-responsive' => ['version' => '4.1.1'],
    'datatables.net-responsive-bs' => ['version' => '4.1.1'],
    'datatables.net-responsive-bs/css/responsive.bootstrap.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-responsive-bs4' => ['version' => '4.1.1'],
    'datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-responsive-bs5' => ['version' => '4.1.1'],
    'datatables.net-responsive-bs5/css/responsive.bootstrap5.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-responsive-dt' => ['version' => '4.1.1'],
    'datatables.net-responsive-dt/css/responsive.dataTables.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-rowgroup' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs/css/rowGroup.bootstrap.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-bs4' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs4/css/rowGroup.bootstrap4.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-bs5' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-bs5/css/rowGroup.bootstrap5.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-bs5/css/rowGroup.bootstrap5.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-rowgroup-dt' => ['version' => '2.1.1'],
    'datatables.net-rowgroup-dt/css/rowGroup.dataTables.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-scroller' => ['version' => '3.1.1'],
    'datatables.net-scroller-bs' => ['version' => '3.1.1'],
    'datatables.net-scroller-bs/css/scroller.bootstrap.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-scroller-bs4' => ['version' => '3.1.1'],
    'datatables.net-scroller-bs4/css/scroller.bootstrap4.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-scroller-bs5' => ['version' => '3.1.1'],
    'datatables.net-scroller-bs5/css/scroller.bootstrap5.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-scroller-dt' => ['version' => '3.1.1'],
    'datatables.net-scroller-dt/css/scroller.dataTables.min.css' => ['version' => '3.1.1', 'type' => 'css'],
    'datatables.net-searchbuilder' => ['version' => '2.1.1'],
    'datatables.net-searchbuilder-bs5' => ['version' => '2.1.1'],
    'datatables.net-searchbuilder-bs5/css/searchBuilder.bootstrap5.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-searchbuilder-bs5/css/searchBuilder.bootstrap5.min.css' => ['version' => '2.1.1', 'type' => 'css'],
    'datatables.net-searchpanes' => ['version' => '2.3.5'],
    'datatables.net-searchpanes-bs5' => ['version' => '2.3.5'],
    'datatables.net-searchpanes-bs5/css/searchPanes.bootstrap5.min.css' => ['version' => '2.3.5', 'type' => 'css'],
    'datatables.net-select' => ['version' => '4.1.1'],
    'datatables.net-select-bs' => ['version' => '4.1.1'],
    'datatables.net-select-bs/css/select.bootstrap.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-select-bs4' => ['version' => '4.1.1'],
    'datatables.net-select-bs4/css/select.bootstrap4.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-select-bs5' => ['version' => '4.1.1'],
    'datatables.net-select-bs5/css/select.bootstrap5.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-select-bs5/css/select.bootstrap5.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'datatables.net-select-dt' => ['version' => '4.1.1'],
    'datatables.net-select-dt/css/select.dataTables.min.css' => ['version' => '4.1.1', 'type' => 'css'],
    'date-fns' => ['version' => '4.4.0'],
    'dexie' => ['version' => '4.4.5'],
    'escape-html' => ['version' => '1.0.3'],
    'flag-icons/css/flag-icons.min.css' => ['version' => '7.5.0', 'type' => 'css'],
    'jquery' => ['version' => '4.0.0'],
    'jszip' => ['version' => '3.10.2'],
    'lucide' => ['version' => '1.52.0'],
    'marked' => ['version' => '18.0.11'],
    'pdfmake' => ['version' => '0.3.11'],
    'pdfmake/build/vfs_fonts.js' => ['version' => '0.3.11'],
    'perfect-scrollbar' => ['version' => '1.5.6'],
    'perfect-scrollbar/css/perfect-scrollbar.min.css' => ['version' => '1.5.6', 'type' => 'css'],
    'simple-datatables' => ['version' => '10.3.0'],
    'simple-datatables/dist/style.min.css' => ['version' => '10.3.0', 'type' => 'css'],
    'stimulus-attributes' => ['version' => '1.0.2'],
];
