<?php

declare(strict_types=1);

namespace App\Service\TranslationWorker;

use App\Message\TranslationWorker\TranslationJobRequest;
use App\Message\TranslationWorker\TranslationResultMessage;
use App\Message\TranslationWorker\WireShape;
use Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter;

/**
 * Turns the worker message DTOs into the Python side of the contract: Pydantic v2 models and a
 * JSON Schema, plus a fingerprint per shape.
 *
 * Reflection over the same constructor properties {@see \App\Messenger\TranslationWorkerCodec}
 * normalizes, with the same snake_case converter — so the generated models describe exactly
 * the bytes Lingua writes and reads. Supported property types are deliberately few (scalars,
 * nullable, backed string enums, nested DTOs, `array<string, X>` maps); anything else throws
 * rather than generating a model that silently disagrees.
 */
final class TranslationContractExporter
{
    /** Top-level shapes on the wire, in the order they are generated. */
    public const array SHAPES = [TranslationJobRequest::class, TranslationResultMessage::class];

    private readonly CamelCaseToSnakeCaseNameConverter $names;

    public function __construct()
    {
        $this->names = new CamelCaseToSnakeCaseNameConverter();
    }

    /**
     * JSON Schema (2020-12) for every shape, nested DTOs and enums under $defs.
     *
     * @return array<string, mixed>
     */
    public function jsonSchema(): array
    {
        $defs = [];
        $oneOf = [];
        foreach (self::SHAPES as $class) {
            $this->define($class, $defs);
            $oneOf[] = ['$ref' => '#/$defs/'.self::short($class)];
        }
        ksort($defs);

        return [
            '$schema' => 'https://json-schema.org/draft/2020-12/schema',
            '$id' => 'https://lingua.survos.com/schema/translation-worker.json',
            'title' => 'Lingua translation worker messages',
            'oneOf' => $oneOf,
            '$defs' => $defs,
        ];
    }

    /**
     * sha256 of one shape's schema (itself plus everything it references). Changes whenever a
     * field is added, removed, renamed, retyped, or its version is bumped.
     *
     * @param class-string $class
     */
    public function fingerprint(string $class): string
    {
        $defs = [];
        $this->define($class, $defs);
        ksort($defs);

        return hash('sha256', json_encode($defs, \JSON_THROW_ON_ERROR | \JSON_UNESCAPED_SLASHES));
    }

    public function python(): string
    {
        $schema = $this->jsonSchema();
        $out = [];
        $out[] = '# GENERATED by Lingua: bin/console lingua:translation-worker:dump-python — DO NOT EDIT.';
        $out[] = '# Source of truth: lingua src/Message/TranslationWorker (#[WireShape] DTOs).';
        $out[] = '# A changed shape gets a new version; regenerate and re-vendor instead of hand-editing.';
        $out[] = 'from __future__ import annotations';
        $out[] = '';
        $out[] = 'from enum import Enum';
        $out[] = 'from typing import Literal, Union';
        $out[] = '';
        $out[] = 'from pydantic import BaseModel, ConfigDict, Field';
        $out[] = '';
        $versions = [];
        $prints = [];
        foreach (self::SHAPES as $class) {
            $shape = WireShape::of($class);
            $versions[] = \sprintf('    %s: %d,', self::py($shape->type), $shape->version);
            $prints[] = \sprintf('    %s: %s,', self::py($shape->type), self::py($this->fingerprint($class)));
        }
        $out[] = 'SHAPE_VERSIONS: dict[str, int] = {';
        array_push($out, ...$versions);
        $out[] = '}';
        $out[] = 'SHAPE_FINGERPRINTS: dict[str, str] = {';
        array_push($out, ...$prints);
        $out[] = '}';

        foreach ($schema['$defs'] as $name => $def) {
            $out[] = '';
            $out[] = '';
            if (isset($def['enum'])) {
                $out[] = "class {$name}(str, Enum):";
                foreach ($def['enum'] as $value) {
                    $out[] = '    '.strtoupper((string) preg_replace('/\W/', '_', $value)).' = '.self::py($value);
                }
                continue;
            }

            $out[] = "class {$name}(BaseModel):";
            if (isset($def['description'])) {
                $out[] = '    """'.$def['description'].'"""';
                $out[] = '';
            }
            // Unknown fields are ignored, as Lingua ignores them; a real change bumps the version.
            $out[] = "    model_config = ConfigDict(extra='ignore')";
            $out[] = '';
            foreach ($def['properties'] as $field => $prop) {
                $required = \in_array($field, $def['required'] ?? [], true);
                $out[] = '    '.$field.': '.$this->pyType($prop).$this->pyDefault($prop, $required);
            }
        }

        $models = array_map(static fn (string $c): string => self::short($c), self::SHAPES);
        $out[] = '';
        $out[] = '';
        $out[] = 'WorkerMessage = Union['.implode(', ', $models).']';
        $out[] = '';

        return implode("\n", $out);
    }

    /** @param array<string, mixed> $defs */
    private function define(string $class, array &$defs): void
    {
        $name = self::short($class);
        if (isset($defs[$name])) {
            return;
        }

        $reflection = new \ReflectionClass($class);
        if ($reflection->isEnum()) {
            $enum = new \ReflectionEnum($class);
            if ((string) $enum->getBackingType() !== 'string') {
                throw new \LogicException($class.' must be a string-backed enum.');
            }
            $values = [];
            foreach ($enum->getCases() as $case) {
                if (!$case instanceof \ReflectionEnumBackedCase) {
                    throw new \LogicException($class.' must be a backed enum.');
                }
                $values[] = (string) $case->getBackingValue();
            }
            $defs[$name] = ['type' => 'string', 'enum' => $values];

            return;
        }

        $defs[$name] = []; // reserve before recursing
        $properties = [];
        $required = [];

        $wire = $reflection->getAttributes(WireShape::class);
        if ($wire !== []) {
            $shape = $wire[0]->newInstance();
            $properties['schema_version'] = ['const' => $shape->version];
            $properties['type'] = ['const' => $shape->type];
            $required = ['schema_version', 'type'];
        }

        $docTypes = self::docParamTypes($reflection->getConstructor()?->getDocComment() ?: '');
        foreach ($reflection->getConstructor()?->getParameters() ?? [] as $param) {
            $field = $this->names->normalize($param->getName());
            $prop = $this->schemaType($param->getType(), $docTypes[$param->getName()] ?? null, $defs, $class.'::$'.$param->getName());
            if ($param->isDefaultValueAvailable()) {
                $prop['default'] = $param->getDefaultValue();
            } else {
                $required[] = $field;
            }
            $properties[$field] = $prop;
        }

        $defs[$name] = ['type' => 'object', 'properties' => $properties, 'required' => $required];
    }

    /**
     * @param array<string, mixed> $defs
     *
     * @return array<string, mixed>
     */
    private function schemaType(?\ReflectionType $type, ?string $docType, array &$defs, string $where): array
    {
        if (!$type instanceof \ReflectionNamedType) {
            throw new \LogicException($where.': only single, optionally nullable types are exportable.');
        }

        $schema = match ($type->getName()) {
            'string' => ['type' => 'string'],
            'int' => ['type' => 'integer'],
            'float' => ['type' => 'number'],
            'bool' => ['type' => 'boolean'],
            'array' => $this->mapType($docType, $where),
            default => (function () use ($type, &$defs): array {
                $this->define($type->getName(), $defs);

                return ['$ref' => '#/$defs/'.self::short($type->getName())];
            })(),
        };

        return $type->allowsNull() ? ['anyOf' => [$schema, ['type' => 'null']]] : $schema;
    }

    /** @return array<string, mixed> */
    private function mapType(?string $docType, string $where): array
    {
        if ($docType === null || !preg_match('/^array<string,\s*([a-z|]+)>$/', $docType, $m)) {
            throw new \LogicException($where.': arrays must be documented as array<string, scalar>.');
        }

        $values = explode('|', $m[1]);
        $item = match (true) {
            $values === ['string'] => ['type' => 'string'],
            $values === ['int'] => ['type' => 'integer'],
            array_diff($values, ['int', 'float']) === [] => ['type' => 'number'],
            default => throw new \LogicException($where.': unsupported map value type '.$m[1].'.'),
        };

        return ['type' => 'object', 'additionalProperties' => $item];
    }

    /** @param array<string, mixed> $prop */
    private function pyType(array $prop): string
    {
        if (isset($prop['const'])) {
            return 'Literal['.self::py($prop['const']).']';
        }
        if (isset($prop['anyOf'])) {
            return $this->pyType($prop['anyOf'][0]).' | None';
        }
        if (isset($prop['$ref'])) {
            return substr($prop['$ref'], \strlen('#/$defs/'));
        }

        return match ($prop['type']) {
            'string' => 'str',
            'integer' => 'int',
            'number' => 'float',
            'boolean' => 'bool',
            'object' => 'dict[str, '.$this->pyType($prop['additionalProperties']).']',
            default => throw new \LogicException('Unsupported schema type.'),
        };
    }

    /** @param array<string, mixed> $prop */
    private function pyDefault(array $prop, bool $required): string
    {
        if (isset($prop['const'])) {
            return ' = '.self::py($prop['const']);
        }
        if ($required) {
            return '';
        }

        return match (true) {
            $prop['default'] === [] => ' = Field(default_factory=dict)',
            default => ' = '.self::py($prop['default']),
        };
    }

    private static function py(mixed $value): string
    {
        return match (true) {
            $value === null => 'None',
            $value === true => 'True',
            $value === false => 'False',
            \is_int($value), \is_float($value) => (string) $value,
            default => json_encode((string) $value, \JSON_THROW_ON_ERROR | \JSON_UNESCAPED_UNICODE | \JSON_UNESCAPED_SLASHES),
        };
    }

    /** @return array<string, string> param name => documented type */
    private static function docParamTypes(string $doc): array
    {
        preg_match_all('/@param\s+(\S+(?:\s*,\s*\S+)?)\s+\$(\w+)/', $doc, $matches, \PREG_SET_ORDER);
        $out = [];
        foreach ($matches as $m) {
            $out[$m[2]] = (string) preg_replace('/\s+/', ' ', $m[1]);
        }

        return $out;
    }

    private static function short(string $class): string
    {
        return substr($class, (int) strrpos($class, '\\') + 1);
    }
}
