<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Adds translation_subscription: who wants to be told when a target string is translated.
 *
 * NOTE: `doctrine:migrations:diff` also emitted `ALTER TABLE target DROP pending_steps` for
 * this migration. That has been REMOVED by hand. It is pre-existing drift — the column is in
 * the database and not in the mapping, from before this change — and dropping a populated
 * column is destructive and has nothing to do with webhooks. It needs its own migration and
 * its own decision; leaving it here would have hidden a data deletion inside a feature commit.
 * Until then `doctrine:schema:validate` will keep reporting the database as out of sync.
 */
final class Version20260817220246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add translation_subscription (webhook subscribers per target string)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE translation_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, callback_url VARCHAR(255) NOT NULL, client_ref VARCHAR(64) NOT NULL, notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, target_key VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D45A4A0F4580895C ON translation_subscription (target_key)');
        $this->addSql('CREATE INDEX subscription_pending_idx ON translation_subscription (notified_at, callback_url)');
        $this->addSql('CREATE UNIQUE INDEX subscription_uq ON translation_subscription (target_key, callback_url)');
        $this->addSql('ALTER TABLE translation_subscription ADD CONSTRAINT FK_D45A4A0F4580895C FOREIGN KEY (target_key) REFERENCES target (key) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE translation_subscription DROP CONSTRAINT FK_D45A4A0F4580895C');
        $this->addSql('DROP TABLE translation_subscription');
    }
}
